### ISSUE TITLE
Resize handler executing code against destroyed service object

### ISSUE THREAD

**Issue by sophypal** [mike-north/ember-resize#137]
We've been hitting this error pretty regularly in our acceptance test and it has been causing chaos on our tests because it errors out while other tests are executing.

`Error: Assertion Failed: calling set on destroyed object: <mcp-ui@service:resize::ember149994>._oldWidthDebounced = 921`

It happens randomly when visiting routes. I think it occurs when the application is destroyed while the resize event or it's handler is still in flight due to the delay introduced by the debounced callback. It's hard to reproduce but happens regularly on our build agents.

**Comment by lmcardle** [comment]
@sophypal we just ran into the same issue. I created a PR to try and fix this: https://github.com/mike-north/ember-resize/pull/140

**Comment by mike-north** [comment]
Fixed in v0.2 thanks to #140
