### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by boris-petrov** [mike-north/ember-resize#149]
Thanks for the great plugin! I see that in `master` you've updated Ember to 2.18 (and most notably `ember-cli-babel` to version 6) - could you release a new version with these changes? This would allow us to remove `ember-cli-shims` and potentially fix some deprecation warnings.

**Comment by MelSumner** [comment]
Hi @mike-north ! Do you need help maintaining this Ember addon? My project uses it and we'd be interested in helping out!

**Comment by Duder-onomy** [comment]
I would also be happy to help. For now, I am using this https://github.com/Duder-onomy/ember-resize-aware
Its similar, uses more modern ember practices and with some features removed.

**Comment by lmcardle** [comment]
+1 Mike. If you need help, happy to lend a hand. We are needing a new version of this addon.

**Comment by mrfisher8432** [comment]
Yes please release a new version with these changes to `ember-cli-babel` as @boris-petrov mentioned above. Thanks!

**Comment by jamesarosen** [comment]
In addition to the stylistic and performance reasons, there's also a security reason: the current version of ember-resize has a dependency (through ember-cli-babel) on minimatch, which patched an important Denial-of-Service vulnerability in 3.0.2.

**Comment by mike-north** [comment]
New version released as 0.2.0
