### ISSUE TITLE
Resize event only firing a few times and then stops completely...

### ISSUE THREAD

**Issue by erichonkanen** [mike-north/ember-resize#20]
Hello,

I just started using this package and noticed that when I resize the browser to be smaller in width, the `didResize` is firing normally. However if I then drag the browser size back up it does not fire and thus my resize code only works in one direction.

Any thoughts or ideas on this?

Thanks!

**Comment by erichonkanen** [comment]
In fact it actually seems like the didResize is only fired a few times initially and then stops working altogether regardless of which direction the resize is going... I pasted code in a separate issue

https://github.com/mike-north/ember-resize/issues/19

**Comment by erichonkanen** [comment]
ps I ended up just rolling my own which seems to work nice... https://gist.github.com/erichonkanen/5f99b072905f696af71f

**Comment by joshuairl** [comment]
@erichonkanen your unbind portion is a bit naive in the sense that it's going to unbind all other events bound to on resize.  So if you have a different component in your app that is bound on resize it won't exist anymore and won't know to rebind itself.

You definitely need a service somehow to manage which listeners exist and which don't, bound by a key so they can be removed by key later.

But I also agree, that this plugin isn't quite functioning as stated in the documentation.

**Comment by joshuairl** [comment]
It seems to work okay with using directly with the service but with the mixin it doesn't work.  Just my experience so far.

**Comment by erichonkanen** [comment]
@joshuairl I see.. yeah I kind of just whipped that up without giving it too much thought..

how could it be enhanced to better handle binding?

**Comment by joshuairl** [comment]
Honestly, the resizeService within this component handles binding / unbinding perfectly.
Uses Ember.Evented on / off.

If I do...

`this.get('resizeService').on('didResize',this.myResizer);` inside of didInsertElement (or wherever).

And then `this.get('resizeService').off('didResize',this.myResizer);` inside of willDestroyElement, etc.

It unbinds only that particular instance and seems to be safe.

Look in the codebase for this plugin for resize service and it should help.

**Comment by erichonkanen** [comment]
What about including namespace? I have this in some other project

```
import Ember from 'ember'

ScrollingMixin = Ember.Mixin.create
  bindScrolling: (namespace)->
    onScroll = ()=>
      Ember.run.debounce(@, ()=>
        @scrolled()
      , 300, true)

    Ember.$(document).bind 'touchmove.' + namespace, onScroll
    Ember.$(window).bind 'scroll.' + namespace, onScroll
  
  unbindScrolling: (namespace)->
    Ember.$(window).unbind 'scroll.' + namespace
    Ember.$(document).unbind 'touchmove.' + namespace

  didInsertElement: ()->
    @_super()
    @bindScrolling(@elementId)

  willDestroyElement: ()->
    @_super()
    @unbindScrolling(@elementId)

export default ScrollingMixin
```

**Comment by joshuairl** [comment]
Well, I don't think you can bind to say... `window.addEventListener('resize.whatever')`.  There is only one "namespace" for this event and it's 'resize' as far as I'm aware.

**Comment by LexLythius** [comment]
I think I don't understand the intent in this mixin. Is it to provide a component-level handler for **window** resize events, or a handler for **component** resize events? One way or the other, the mixin is broken.

The issue that bit @erichonkanen and me lies in the `_handleResizeEvent` and `_getComponentSize` methods:

````javascript
  _getComponentSize() {
    return this.$()[0].getClientRects()[0];
  },

  _handleResizeEvent(evt) {
    const w = floor(this._getComponentSize().width);
    const h = floor(this._getComponentSize().height);
    if ((this.get('resizeWidthSensitive') && (this.get('_oldViewWidth') !== w)) ||
      (this.get('resizeHeightSensitive') && (this.get('_oldViewHeight') !== h))) {
      this.didResize(w, h, evt);
      this.setProperties({
        _oldViewWidth: w,
        _oldViewHeight: h
      });
    }
  },
````
The event is triggered by the resize service, which observes the **window** object, while `_getComponentSize` measures the **component**. Therefore, the comparison that takes place in `_handleResizeEvent` is based on the wrong object!

My ugly but simple and effective solution: overriding `_handleResizeEvent or `_handleDebouncedResizeEvent` as needed:
````javascript
	_handleDebouncedResizeEvent: function (evt) {
		this._super(...arguments); // this would handle the object itself resizing

		// but we're more interested in window resize, which the mixin doesn't handle well:
		if (evt.target === window) {
			// DO SOMETHING HERE
		}
	},
````

A definitive solution requires clarification of what the mixin intends to react to.

**Comment by mike-north** [comment]
@lexlythius - there is only one resize event, and it fires whenever the browser viewport dimensions are changed. 

The intent is to provide an idiomatic way of responding to this event, with a little sugar that make several common use cases easier

**Comment by SirZach** [comment]
I've noticed the service only works when resizing widths, not heights.
