### ISSUE TITLE
0.3.1 not published

### ISSUE THREAD

**Issue by kellyselden** [mike-north/ember-resize#285]
I think there may have been an issue with your deployment.

**Comment by mike-north** [comment]
Will look into it today

**Comment by mike-north** [comment]
When you see a notification from a semantic-release bot in this issue, it's an indication that a new patch release will have gone out.

**Comment by mike-north** [comment]
[0.3.4 released](https://github.com/mike-north/ember-resize/releases/tag/v0.3.4)
