### ISSUE TITLE
Respond to orientationchange event?

### ISSUE THREAD

**Issue by jblotus** [mike-north/ember-resize#47]
Does it make sense to add a listener or method for orientationchange? is that outside of the scope of this addon?

**Comment by sheriffderek** [comment]
I'm not sure how you would find that per device, but generally - you can have knowledge of the orientation by comparing the width and height in an expression.

**Comment by mike-north** [comment]
@jblotus did you take a look at https://github.com/mike-north/ember-orientation ?

**Comment by jblotus** [comment]
@mike-north i'll give ember-orientation a try. My use case is that I'm trying to listen to resize some element when the screen is resized or the screen is rotated. I mistakenly assumed that orientationchange would trigger a resize event.
