### ISSUE TITLE
Mix-in vs. Service: different behaviour when used in a component

### ISSUE THREAD

**Issue by myartsev** [mike-north/ember-resize#82]
The mix-in event will fire only when the **component itself is resized**.
The service event will fire **whenever the entire window is resized**.

Is this intentional? The readme documentation makes it sound like the two are equivalent.
https://ember-twiddle.com/7ba80efb25e56c2dd7b9baa9aadec42e

**Comment by mike-north** [comment]
This is working as intended, and the main reason for the mixin to exist
