### ISSUE TITLE
Doesn't seem to be doing anything in ember-cli 2.10.0?

### ISSUE THREAD

**Issue by jfrux** [mike-north/ember-resize#88]
I've tried both the mixin and the service in a controller and it doesn't seem to console.log when resizing.  Hmm...

I'm sure it's something I'm doing but I can't get it to work.

**Comment by mike-north** [comment]
Can you create an example project demonstrating the problem, so I can take a look?

**Comment by erichonkanen** [comment]
+1 I just installed this and tried getting it working in controller and component and nothing is happening(?)

`DEBUG: Ember             : 2.12.1`

**Comment by erichonkanen** [comment]
I want to note that the following code works, so it seems like the mixin is what doesn't work? Ideally I don't have to override `init()` for any object that wants to use this...

```export default Ember.Controller.extend({
  init() {
    this._super(...arguments);
    this.get('resizeService').on('didResize', (e) => {
      debugger;
    });
  },
```

**Comment by andycochran** [comment]
Any update on getting the mixin to work w/ newer Ember versions?

**Comment by mike-north** [comment]
I've verified that this works with the latest three LTS releases, current, beta and canary
